# 错误处理

- 错误表示为遵守 Error 协议的值
- 可使用 枚举遵守 Error 协议 表示错误的不同种类
- 错误可以被抛出 throw 错误值

# 处理错误的四种方法

## try + 抛出错误的函数

1. 使用抛出函数 传递错误
2. throws 放在 形式参数 后 , -> 之前
3. 函数内部 throw + 错误
4. 只有抛出函数可以传递错误
5. 调用 throw 的错误:
    1. try + 方法

## do - catch 处理

- 根据捕获的错误类型 执行不同的操作
    
    ```swift
    do {
        try expression
        statements
    } catch err 1 {
        statements
    } catch err 2 where condition {
        statements
    } catch err 3, err 4 where condition {
        statements
    } catch {   //此处会匹配剩余未表示的所有错误
        statements
    }
    ```
    
- 若 catch 到的 错误未被处理传到顶层 会触发运行时错误
- catch 不使用错误 作为条件

## err 作为 可选项的值 传出

### try?

- var a = try? + 抛出错误的函数
- 一般作为赋值语句使用
- 函数若有错误被抛出 , a 将为 nil
- 无错误 a 将存储 函数的返回值

### try!

- 不进行错误检查
- 保证错误不会发生时使用
- 发生错误则运行时报错

## 错误发生 及断言 assert

- 调用 assert 函数

# defer

- 后加 执行到离开作用域时 会执行的代码段